# -*- coding: utf-8 -*-
"""Copy of Me 360 pipette script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_LovnikXLGBEdUzA02bn207ZvGm9s048
"""

def generate_pipetter_gcode(filename, move_speed=3000, lower_speed1=300, lower_speed2=40):
    commands = [
        "; Start of G-code",
        "G28 ; Home all axes",
        f"G1 X0 Y0 Z0 E045 F{move_speed}"
    ]

    maxX=200
    maxY=165
    hole1x=145
    hole1y=20
    cup1x=159
    cup1y=88
    stepsize=9
    endmove1=45
    lowerdist1=5



    for i in range(1,9):
      cup1y=cup1y+stepsize*(i-1)
      cup1x=159
      for col in range(1,13):
            # Move to fluid cup
            commands.append(f"G1 Y{hole1y} X{hole1x} F{move_speed}")
            commands.append(f"G1 Z{lowerdist1} F{lower_speed1}")
            commands.append(f"G1 E00 F{1000}")
            commands.append(f"G1 E0{endmove1} F{1000}")
            commands.append(f"G1 Z2 F{lower_speed2}")

            # Move to plate hole
            commands.append(f"G1 Y{cup1y} X{cup1x} F{move_speed}")
            commands.append(f"G1 Z{lowerdist1} F{lower_speed1}")
            commands.append(f"G1 E00 F{1000}")
            commands.append(f"G1 E0{endmove1} F{1000}")
            commands.append(f"G1 Z2 F{lower_speed2}")

            cup1x -= stepsize


    with open(filename, 'w') as file:
        for cmd in commands:
            file.write(cmd + '\n')

    print(f"G-code written to {filename} in current Colab directory.")

# Run it
generate_pipetter_gcode("pipetter_output.gcode")

